### ISSUE TITLE
Pebble SDK 2 and JellyTime

### ISSUE THREAD

**Issue by darkmorpher** [zalewszczak/pebble#3]
Is it possible to use Pebble SDK 2 and pull weather data? Also, if you are using Roboto font, a new version has been released.

#wontfix

**Comment by zalewszczak** [comment]
It would be possible, I just haven't ported that watchface to SDK 2.0 (did not have time to port every single one and now I have many requests for other watchfaces). I might remake this watchface in the future, and use latest version of roboto doing so. Right now I can't promise anything.
